//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digigarage.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Description { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Service Service { get; set; }
        public virtual StautsOfBooking StautsOfBooking { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
