//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HMSEntities : DbContext
    {
        public DB_HMSEntities()
            : base("name=DB_HMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Bookings> tbl_Bookings { get; set; }
        public virtual DbSet<tbl_Hotels> tbl_Hotels { get; set; }
        public virtual DbSet<tbl_Rooms> tbl_Rooms { get; set; }
    }
}
