//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bookings
    {
        public int bID { get; set; }
        public System.DateTime bDate { get; set; }
        public string bStatus { get; set; }
        public int rID { get; set; }
    
        public virtual tbl_Rooms tbl_Rooms { get; set; }
    }
}
