//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Rooms()
        {
            this.tbl_Bookings = new HashSet<tbl_Bookings>();
        }
    
        public int rID { get; set; }
        public string rName { get; set; }
        public string rCategory { get; set; }
        public double rPrice { get; set; }
        public bool rIsActive { get; set; }
        public System.DateTime rCreatedDate { get; set; }
        public string rCreatedBy { get; set; }
        public System.DateTime rUpdatedDate { get; set; }
        public string rUpdatedBy { get; set; }
        public Nullable<int> hID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bookings> tbl_Bookings { get; set; }
        public virtual tbl_Hotels tbl_Hotels { get; set; }
    }
}
