//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hotels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Hotels()
        {
            this.tbl_Rooms = new HashSet<tbl_Rooms>();
        }
    
        public int hID { get; set; }
        public string hName { get; set; }
        public string hAddress { get; set; }
        public string hCity { get; set; }
        public int hPincode { get; set; }
        public string hContactNumber { get; set; }
        public string hContactPerson { get; set; }
        public string hWebsite { get; set; }
        public string hFacebook { get; set; }
        public string hTwitter { get; set; }
        public bool hIsActive { get; set; }
        public System.DateTime hCreatedDate { get; set; }
        public string hCreatedBy { get; set; }
        public System.DateTime hUpdatedDate { get; set; }
        public string hUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Rooms> tbl_Rooms { get; set; }
    }
}
