//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Services
    {
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public double Price { get; set; }
        public string Duration { get; set; }
        public bool IsActive { get; set; }
        public int mechanicID { get; set; }
    
        public virtual tbl_Mechanics tbl_Mechanics { get; set; }
    }
}
