//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vehicles
    {
        public int ID { get; set; }
        public string licensePlate { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public System.DateTime registrationDate { get; set; }
        public string chasisNo { get; set; }
        public int custID { get; set; }
    
        public virtual tbl_Customers tbl_Customers { get; set; }
    }
}
