//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlFinalAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using SourceControlFinalAssignment.Custom_Validation;

    public partial class tblUserDetails
    {
        [Key]
        public int uID { get; set; }

        [Required(ErrorMessage = "Enter Username!")]
        [Display(Name = "Username")]
        [StringLength(maximumLength: 11, MinimumLength = 3, ErrorMessage = "Username must be max 11 and min 3")]
        public string uName { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Enter Email")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string uEmail { get; set; }

        [Required(ErrorMessage = "Enter Password.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(8)]
        public string uPassword { get; set; }

        [Required(ErrorMessage = "Enter Confirm Password.")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("uPassword")]
        public string uConfirmPassword { get; set; }

        [Display(Name = "Age")]
        [Required(ErrorMessage = "Enter Age")]
        [Range(18, 60, ErrorMessage = "Age Must be between 18 to 60")]
        public Nullable<int> uAge { get; set; }

        [DataType(DataType.MultilineText)]
        [MaxWordAttributes(70)]
        [Display(Name = "Address")]
        public string uAddress { get; set; }

        [Required(ErrorMessage = "Enter Contact Number.")]
        [Display(Name = "Contact Number")]
        [MaxLength(10)]
        [DataType(DataType.PhoneNumber)]
        public string uPhone { get; set; }

        [Required(ErrorMessage = "Upload Profile Picture")]
        [Display(Name = "Profile Picture")]
        public string uProfileImg { get; set; }
    }
}
