//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Users
    {
        [Key]
        public int User_ID { get; set; }

        [Required(ErrorMessage = "Enter Email Address")]
        [EmailAddress]
        [Display(Name = "Email ID")]
        public string User_Name { get; set; }

        [Required(ErrorMessage = "Enter Password")]
        [MinLength(8)]
        [DataType(DataType.Password)]
        [Display(Name ="Password")]
        public string User_Password { get; set; }

        [Required(ErrorMessage = "Enter Confirm Password")]
        [MinLength(8)]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        public string User_ConfirmPassword { get; set; }
    }
}
