//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Context
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tbl_Products
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public string SmallImg { get; set; }
        public string LargeImg { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
