//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_VMSEntities : DbContext
    {
        public DB_VMSEntities()
            : base("name=DB_VMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Customers> tbl_Customers { get; set; }
        public virtual DbSet<tbl_Mechanics> tbl_Mechanics { get; set; }
        public virtual DbSet<tbl_Services> tbl_Services { get; set; }
        public virtual DbSet<tbl_Vehicles> tbl_Vehicles { get; set; }
    }
}
